language: erlang
otp_release:
  - R15B
  - R15B01
  - R15B02
  - R16B
branches:
  only:
    - master
    - develop
    - /^hotfix-.*/
    - /^release-.*/
notifications:
  email:
    recipients:
      - kgadek+travisci@gmail.com
    on_success: never
    on_failure: always
